version: '3.5'
networks:
  sensor-streaming:
    name: sensor-streaming
    driver: bridge
services:
  influxdb:
    image: influxdb:1.6-alpine
    container_name: influxdb
    ports:
    - "8086:8086"
    environment:
    - INFLUXDB_DB=sensors
    - INFLUXDB_USER=admin
    - INFLUXDB_USER_PASSWORD=admin
    networks:
    - sensor-streaming
  grafana:
    image: grafana/grafana:5.3.1
    container_name: grafana
    ports:
    - "3000:3000"
    volumes:
    - ./env/grafana/provisioning:/etc/grafana/provisioning
    - ./env/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
    - sensor-streaming